# Generated by Django 5.1.1 on 2025-10-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_collaboratorapplication_user_bathroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboratorapplication',
            name='address_proof_text',
            field=models.TextField(blank=True),
        ),
    ]
