# Generated by Django 5.1.1 on 2025-10-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_fix_address_proof_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboratorapplication',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='collaboratorapplication',
            name='website',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
