# Generated by Django 5.1.1 on 2025-11-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_collaboratorapplication_photo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboratorapplication',
            name='photo_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='collaboratorapplication',
            name='website',
            field=models.TextField(blank=True),
        ),
    ]
